# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_constraints.xdc

# Block Designs: bd/bram/bram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram || ORIG_REF_NAME==bram}]

# IP: bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_blk_mem_gen_0_0}]

# XDC: bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/bram/bram_ooc.xdc
