# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.cache/wt [current_project]
set_property parent.project_path C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
add_files //puma.student.lth.se/mi3105is-s/Downloads/BG_Street.coe
add_files //puma.student.lth.se/mi3105is-s/Downloads/CurvyStreet.coe
add_files -quiet c:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/bd/bram/bram.bd
set_property used_in_implementation false [get_files -all c:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/bd/bram/bram_ooc.xdc]
set_property is_locked true [get_files C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/bd/bram/bram.bd]

read_vhdl -library xil_defaultlib {
  C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/new/Address_counter_new.vhd
  C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/imports/hdl/bram_wrapper.vhd
  C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/new/bram_top.vhd
  C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/imports/vhdl/vga_controller_640_60.vhd
  C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/imports/vhdl/vga_ref_pack.vhd
  C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/sources_1/imports/vhdl/vga_ref.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/constrs_1/new/vga_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/mi3105is-s/Program/CrazyCarBackground/Working/Working.srcs/constrs_1/new/vga_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top vga_ref -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vga_ref.dcp

catch { report_utilization -file vga_ref_utilization_synth.rpt -pb vga_ref_utilization_synth.pb }
